# -*- coding: utf-8 -*-
"""week 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvNDh33mw7FdwElS9wtz9cTZCAHaG2Ej
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

from tensorflow.keras.applications import VGG19
from tensorflow.keras.applications.vgg19 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model

def load_img(path):
    img = image.load_img(path, target_size=(224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    return img

content_path = "content.jpg"
style_path = "style.jpg"

content_image = load_img(content_path)
style_image = load_img(style_path)

def show_img(img, title=None):
    img = img.reshape((224,224,3))
    img[:,:,0] += 103.939
    img[:,:,1] += 116.779
    img[:,:,2] += 123.68
    img = img[:,:,::-1]
    img = np.clip(img,0,255).astype('uint8')

    plt.imshow(img)
    if title:
        plt.title(title)
    plt.axis('off')

plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
show_img(content_image, "Content Image")

plt.subplot(1,2,2)
show_img(style_image, "Style Image")

vgg = VGG19(weights='imagenet', include_top=False)

for layer in vgg.layers:
    layer.trainable = False

content_layers = ['block5_conv2']

style_layers = [
    'block1_conv1',
    'block2_conv1',
    'block3_conv1',
    'block4_conv1',
    'block5_conv1'
]

outputs = [vgg.get_layer(name).output for name in style_layers + content_layers]

model = Model(inputs=vgg.input, outputs=outputs)

def gram_matrix(tensor):
    result = tf.linalg.einsum('bijc,bijd->bcd', tensor, tensor)
    shape = tf.shape(tensor)
    num_locations = tf.cast(shape[1]*shape[2], tf.float32)
    return result / num_locations

def content_loss(base, target):
    return tf.reduce_mean(tf.square(base - target))

def style_loss(base, target):
    gram_base = gram_matrix(base)
    gram_target = gram_matrix(target)
    return tf.reduce_mean(tf.square(gram_base - gram_target))

style_targets = model(style_image)[:len(style_layers)]
content_targets = model(content_image)[len(style_layers):]

content_weight = 1e4
style_weight = 1e-2

def total_loss(outputs):

    style_outputs = outputs[:len(style_layers)]
    content_outputs = outputs[len(style_layers):]

    s_loss = 0
    for s_out, s_target in zip(style_outputs, style_targets):
        s_loss += style_loss(s_out, s_target)

    c_loss = 0
    for c_out, c_target in zip(content_outputs, content_targets):
        c_loss += content_loss(c_out, c_target)

    total = style_weight*s_loss + content_weight*c_loss
    return total

generated_image = tf.Variable(content_image, dtype=tf.float32)

optimizer = tf.optimizers.Adam(learning_rate=0.02)

epochs = 300

for i in range(epochs):

    with tf.GradientTape() as tape:
        outputs = model(generated_image)
        loss = total_loss(outputs)

    grads = tape.gradient(loss, generated_image)
    optimizer.apply_gradients([(grads, generated_image)])

    if i % 50 == 0:
        print("Iteration:", i, "Loss:", loss.numpy())

def deprocess(img):
    img = img.reshape((224,224,3))
    img[:,:,0] += 103.939
    img[:,:,1] += 116.779
    img[:,:,2] += 123.68
    img = img[:,:,::-1]
    img = np.clip(img,0,255).astype('uint8')
    return img

result = deprocess(generated_image.numpy())

plt.figure(figsize=(6,6))
plt.imshow(result)
plt.title("Stylized Image")
plt.axis('off')